/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blissapplications_ble_BluetoothCentralManager */

#ifndef _Included_com_blissapplications_ble_BluetoothCentralManager
#define _Included_com_blissapplications_ble_BluetoothCentralManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    initialize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    getState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_getState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    startScanPeripherals
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_startScanPeripherals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    stopScanPeripherals
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_stopScanPeripherals
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    connectPeripheral
 * Signature: (JJLcom/blissapplications/ble/BluetoothConnectPeripheralOptions;)V
 */
JNIEXPORT void JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_connectPeripheral
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    cancelPeripheralConnection
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_cancelPeripheralConnection
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    deinitialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_deinitialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    retrievePeripheralsWithIdentifiers
 * Signature: (J[Ljava/util/UUID;)[Lcom/blissapplications/ble/BluetoothPeripheral;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_retrievePeripheralsWithIdentifiers
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     com_blissapplications_ble_BluetoothCentralManager
 * Method:    retrieveConnectedPeripheralsWithServices
 * Signature: (J[Ljava/util/UUID;)[Lcom/blissapplications/ble/BluetoothPeripheral;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blissapplications_ble_BluetoothCentralManager_retrieveConnectedPeripheralsWithServices
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
