/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blissapplications_ble_BluetoothCharacteristic */

#ifndef _Included_com_blissapplications_ble_BluetoothCharacteristic
#define _Included_com_blissapplications_ble_BluetoothCharacteristic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blissapplications_ble_BluetoothCharacteristic
 * Method:    getIdentifier
 * Signature: (J)Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_com_blissapplications_ble_BluetoothCharacteristic_getIdentifier
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCharacteristic
 * Method:    getValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_blissapplications_ble_BluetoothCharacteristic_getValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCharacteristic
 * Method:    getProperties
 * Signature: (J)Lcom/blissapplications/ble/BluetoothCharacteristicProperties;
 */
JNIEXPORT jobject JNICALL Java_com_blissapplications_ble_BluetoothCharacteristic_getProperties
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCharacteristic
 * Method:    getDescriptors
 * Signature: (J)[Lcom/blissapplications/ble/BluetoothDescriptor;
 */
JNIEXPORT jobjectArray JNICALL Java_com_blissapplications_ble_BluetoothCharacteristic_getDescriptors
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_blissapplications_ble_BluetoothCharacteristic
 * Method:    isNotifying
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_blissapplications_ble_BluetoothCharacteristic_isNotifying
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
