/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blissapplications_ble_BluetoothDescriptor */

#ifndef _Included_com_blissapplications_ble_BluetoothDescriptor
#define _Included_com_blissapplications_ble_BluetoothDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blissapplications_ble_BluetoothDescriptor
 * Method:    getIdentifier
 * Signature: (J)Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_com_blissapplications_ble_BluetoothDescriptor_getIdentifier
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
